import { connect } from "@/db/dbConfig";
import User from "@/db/models/userSchema";
import Client from "@/db/models/clientSchema";
import { NextResponse } from "next/server";
import Project from "@/db/models/projectSchema";

connect();
export async function POST() {
  const response = await Project.insertMany([
    {
      projectname: "AquaScape",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa21",
      clientname: "Megan Johnson",
      technology: "React.js",
      hoursAlloted: 800,
      hoursConsumed: 650,
      hoursLeft: 150,
      description: "Aquarium Management System",
      assignedTeam: ["Developer: Emily Wilson", "Designer: Ethan Brown"],
    },
    {
      projectname: "EduVista",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa22",
      clientname: "Daniel Roberts",
      technology: "Vue.js",
      hoursAlloted: 1200,
      hoursConsumed: 950,
      hoursLeft: 250,
      description: "Educational Platform for Students",
      assignedTeam: ["Developer: Sophia Garcia", "Designer: Matthew Lee"],
    },
    {
      projectname: "HomeFit",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "Angular",
      hoursAlloted: 1000,
      hoursConsumed: 800,
      hoursLeft: 200,
      description: "Home Fitness App",
      assignedTeam: ["Developer: Lucas Moore", "Designer: Olivia Parker"],
    },
    {
      projectname: "MarketMax",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa21",
      clientname: "Megan Johnson",
      technology: "Node.js",
      hoursAlloted: 1200,
      hoursConsumed: 900,
      hoursLeft: 300,
      description: "E-commerce Analytics Platform",
      assignedTeam: ["Developer: Ethan Adams", "Designer: Lily White"],
    },
    {
      projectname: "ArtisticAura",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "React Native",
      hoursAlloted: 1000,
      hoursConsumed: 750,
      hoursLeft: 250,
      description: "Art Gallery Mobile App",
      assignedTeam: ["Developer: Mason King", "Designer: Ava Collins"],
    },
    {
      projectname: "EventEssence",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa22",
      clientname: "Daniel Roberts",
      technology: "Flutter",
      hoursAlloted: 1500,
      hoursConsumed: 1100,
      hoursLeft: 400,
      description: "Event Management Platform",
      assignedTeam: ["Developer: Harper Scott", "Designer: Noah Green"],
    },
    {
      projectname: "SocialPulse",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "Express.js",
      hoursAlloted: 800,
      hoursConsumed: 600,
      hoursLeft: 200,
      description: "Social Media Analytics Tool",
      assignedTeam: ["Developer: Zoey Turner", "Designer: Liam Harris"],
    },
    {
      projectname: "MindMesh",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa21",
      clientname: "Megan Johnson",
      technology: "Java Spring",
      hoursAlloted: 1200,
      hoursConsumed: 900,
      hoursLeft: 300,
      description: "Collaborative Mind Mapping Tool",
      assignedTeam: ["Developer: Chloe Martinez", "Designer: Ethan Clark"],
    },
    {
      projectname: "HealthHive",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa22",
      clientname: "Daniel Roberts",
      technology: "ASP.NET Core",
      hoursAlloted: 1000,
      hoursConsumed: 750,
      hoursLeft: 250,
      description: "Healthcare Management System",
      assignedTeam: [
        "Developer: Isabella Rodriguez",
        "Designer: Benjamin Baker",
      ],
    },
    {
      projectname: "MediaMagic",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "Ruby on Rails",
      hoursAlloted: 800,
      hoursConsumed: 700,
      hoursLeft: 100,
      description: "Media Content Management System",
      assignedTeam: ["Developer: Lucas Turner", "Designer: Sophia Martinez"],
    },
    {
      projectname: "CodeCraft",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa21",
      clientname: "Megan Johnson",
      technology: "Python Django",
      hoursAlloted: 1200,
      hoursConsumed: 900,
      hoursLeft: 300,
      description: "Code Collaboration Platform",
      assignedTeam: ["Developer: Chloe Martinez", "Designer: Ethan Clark"],
    },
    {
      projectname: "SmartServe",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa22",
      clientname: "Daniel Roberts",
      technology: "Laravel",
      hoursAlloted: 1000,
      hoursConsumed: 750,
      hoursLeft: 250,
      description: "Smart Restaurant Management System",
      assignedTeam: [
        "Developer: Isabella Rodriguez",
        "Designer: Benjamin Baker",
      ],
    },
    {
      projectname: "DigitalDazzle",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "Express.js",
      hoursAlloted: 800,
      hoursConsumed: 700,
      hoursLeft: 100,
      description: "Digital Marketing Analytics Tool",
      assignedTeam: ["Developer: Lucas Turner", "Designer: Sophia Martinez"],
    },
    {
      projectname: "BizBuzz",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa21",
      clientname: "Megan Johnson",
      technology: "Ruby on Rails",
      hoursAlloted: 1200,
      hoursConsumed: 900,
      hoursLeft: 300,
      description: "Business Networking Platform",
      assignedTeam: ["Developer: Chloe Martinez", "Designer: Ethan Clark"],
    },
    {
      projectname: "CloudCraze",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa22",
      clientname: "Daniel Roberts",
      technology: "React.js",
      hoursAlloted: 1000,
      hoursConsumed: 750,
      hoursLeft: 250,
      description: "Cloud Management Dashboard",
      assignedTeam: [
        "Developer: Isabella Rodriguez",
        "Designer: Benjamin Baker",
      ],
    },
    {
      projectname: "TechTrend",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "Vue.js",
      hoursAlloted: 800,
      hoursConsumed: 700,
      hoursLeft: 100,
      description: "Technology News Aggregator",
      assignedTeam: ["Developer: Lucas Turner", "Designer: Sophia Martinez"],
    },
    {
      projectname: "DataDrive",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa21",
      clientname: "Megan Johnson",
      technology: "Angular",
      hoursAlloted: 1200,
      hoursConsumed: 900,
      hoursLeft: 300,
      description: "Data Management Platform",
      assignedTeam: ["Developer: Chloe Martinez", "Designer: Ethan Clark"],
    },
    {
      projectname: "MarketMate",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa22",
      clientname: "Daniel Roberts",
      technology: "React Native",
      hoursAlloted: 1000,
      hoursConsumed: 750,
      hoursLeft: 250,
      description: "Marketing Automation App",
      assignedTeam: [
        "Developer: Isabella Rodriguez",
        "Designer: Benjamin Baker",
      ],
    },
    {
      projectname: "HealthHero",
      adminId: "660bee9d470e203b92d3f9a8",
      client: "660bef24470e203b92d3fa24",
      clientname: "Sarah Miller",
      technology: "Flutter",
      hoursAlloted: 800,
      hoursConsumed: 700,
      hoursLeft: 100,
      description: "Health Monitoring App",
      assignedTeam: ["Developer: Lucas Turner", "Designer: Sophia Martinez"],
    },
  ]);
  return NextResponse.json({ message: "Voila" });
}
